version: '3'

services:
  authorization-server:
    build: .
    volumes:
      - ./dist:/usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - 3002:3002
      - 9228:9229
    command: npm run map-debug